class_name LevelGeneration extends Node3D

enum NoiseMapType
{
	ALL_BLACK = 0,
	ALL_WHITE = 1,
	PERLIN_NOISE = 2
}

enum RandomizeMode
{
	RANDOM = 0,  # Uses `randi()` to randomize
	RNG = 1,  # Uses `RandomNumberGenerator.randi()` to randomize
	INDEX = 2,
	# About INDEX:
	# For the level generator, it uses `pos.y * pos.x + pos.y * pos.z + pos.x - pos.z + pos.y * 5`, where `pos` is the global position of the chunk
	# For the chunk generator modules, it uses the module index in the list
	PARENT = 3
	# About PARENT:
	# Uses the parent's seed
	# This value will always be 0 for the level generator
}

var _GeneratedChunksContainer: Node3D
var _ChunkConstants: Node3D
var _Seed: int = 0
var _RNG: RandomNumberGenerator = RandomNumberGenerator.new()

@export_category("Generation")
var GenerationRadius: int = 20  # Radius where the chunks will be generated

@export_group("Noise maps")
@export var NoiseMaps: Dictionary[String, Image] = {}
@export var DefaultNoiseMapType: NoiseMapType = NoiseMapType.PERLIN_NOISE
@export var DefaultNoiseMapSize: Vector2i = Vector2i(1024, 1024)

@export_group("Floors")
@export var MaxFloors: Vector2i = Vector2i(0, 0)  # X = down limit, Y = up limit, (0, 0) = no floors
@export var PreloadFloors: Vector2i = Vector2i(0, 0)  # Number of floors to preload. X = down, Y = up, (0, 0) = no preload
# More about preloaded floors:
# Preloaded floors are NOT generated by the server; only by the client
# Because of this, preloaded floors might not have items nor entities, until the player goes there

@export_category("Chunks")
@export var GeneralChunkSize: Vector3i = Vector3i(20, 6, 20)
@export var ChunkRandomizeMode: RandomizeMode = RandomizeMode.INDEX

static func CalculateSeedForObject(
	Mode: RandomizeMode,
	Obj: Node,
	RNG: RandomNumberGenerator = null,
	ModuleIdx: int = -1,
	Position: Vector3 = Vector3.ZERO
) -> int:
	# Check the randomize mode
	match Mode:
		RandomizeMode.RANDOM:
			# Totally random seed
			return randi()
		RandomizeMode.RNG:
			# Random seed based of the RandomNumberGenerator
			# Make sure the RandomNumberGenerator is not null
			if (RNG == null):
				# It is null; return 0
				return 0
			
			# Return a random number from the RandomNumberGenerator
			return RNG.randi()
		RandomizeMode.INDEX:
			# NOT random seed, based of the position (if it's a level generator) or the modules index (if it's a chunk generator module)
			# Check the object type
			if (Obj is LevelGeneration):
				# The object is a level generator
				# Return a position-based seed
				return absi(int(Position.y * Position.x + Position.y * Position.z + Position.x - Position.z + Position.y * 5))
			elif (Obj is ChunkModuleBase):
				# The object is expected to be a chunk generator or module
				# Return an index-based seed (module index)
				return ModuleIdx
			
			# Invalid object type, push error
			push_error("Invalid object type for index-based randomization.")
		RandomizeMode.PARENT:
			# NOT random seed, the same as the parent of the object
			# Check the object type
			if (Obj is LevelChunk):
				# The object is a chunk generator
				# Return the seed from the level generator
				return Obj.get_parent().get_parent()._Seed
			
			# The object type is NOT a chunk generator; try to get the seed from it's parent (return 0 if no seed is found in the parent)
			return Obj.get_parent()._Seed if ("_Seed" in Obj.get_parent()) else Obj.get_parent().Seed if ("Seed" in Obj.get_parent()) else 0
		_:
			push_error("Invalid randomize mode. 0 will be returned instead.")
	
	# Return 0 as a fallback
	return 0

func CreateFloorImage() -> Image:
	const FORMAT = Image.FORMAT_RGBA8
	var img
	
	# Check image type
	match DefaultNoiseMapType:
		NoiseMapType.ALL_BLACK:
			# Create black image
			img = Image.create(DefaultNoiseMapSize.x, DefaultNoiseMapSize.y, false, FORMAT)
			img.fill(Color.BLACK)
		NoiseMapType.ALL_WHITE:
			# Create white image
			img = Image.create(DefaultNoiseMapSize.x, DefaultNoiseMapSize.y, false, FORMAT)
			img.fill(Color.WHITE)
		NoiseMapType.PERLIN_NOISE:
			# Create an image with perlin noise
			var perlin = FastNoiseLite.new()
			perlin.noise_type = FastNoiseLite.TYPE_PERLIN
			
			img = perlin.get_image(DefaultNoiseMapSize.x, DefaultNoiseMapSize.y, false, false, true)
		_:
			# Invalid option; push error
			push_error("Invalid NoiseMapType. Image will not be generated (null will be returned instead).")
	
	# Return the image
	return img

func GetFloorTexture(Floor: int) -> Image:
	var img = null
	
	# For each key in the noise maps (example of a key: "0,1,5")
	for floorsUnparsed in NoiseMaps.keys():
		# Split the string and for each new string (example: "0")
		for floorIDX in floorsUnparsed.split(","):
			# Strip the edges of the string (example: " 0 " => "0")
			floorIDX = floorIDX.strip_edges(true, true)
			
			# Parse the string as an integer (example: "0" => 0)
			floorIDX = int(floorIDX)
			
			# Check if the desired floor is this one
			if (Floor == floorIDX):
				# It is! Set the image with the noise map and stop the loop
				img = NoiseMaps[floorsUnparsed]
				break
		
		# Stop the loop of the image is set (the desired floor was found)
		if (img != null):
			break
	
	# If the image is not set (the desired floor was not found), create an image
	if (img == null):
		img = CreateFloorImage()
	
	# Return the image
	return img

func GetChunkIndexFromFloorTexture(Floor: Image, ChunkPosXZ: Vector2i) -> int:
	# ChunkPosXZ must be the GLOBAL POSITION (x, z)
	# Calculate the pixel position in the image
	var pixelPos = Vector2i(
		ChunkPosXZ.x % Floor.get_width(),
		ChunkPosXZ.y % Floor.get_height()
	)
	
	# Make sure the pixel is inside the image
	while (pixelPos.x < 0): pixelPos.x += Floor.get_width()
	while (pixelPos.y < 0): pixelPos.y += Floor.get_height()
	while (pixelPos.x > Floor.get_width()): pixelPos.x -= Floor.get_width()
	while (pixelPos.y > Floor.get_height()): pixelPos.y -= Floor.get_height()
	
	# Get the G parameter from the pixel's color in the image, then multiply it by the size of the chunk constants, and round it
	# This returns the exact chunk index
	return roundi(int(Floor.get_pixel(pixelPos.x, pixelPos.y).g * (_ChunkConstants.get_children(false).size() - 1)))

func GenerateChunk(Position: Vector3i, ChunkIdx: int, NearbyChunks: PackedInt32Array) -> Node3D:
	# Position must be the GLOBAL POSITION
	# Make sure the chunk index is valid
	if (ChunkIdx >= _ChunkConstants.get_children(false).size()):
		# Invalid chunk index, push error
		push_error("Could not generate chunk: invalid index. Null will be returned instead.")
		return null
	
	# The chunk index is valid, continue generation
	var generatedChunk: LevelChunk = _ChunkConstants.get_children(false)[ChunkIdx].duplicate()  # Duplicate the selected chunk. The chunk MUST be a LevelChunk or derivated
	generatedChunk.reparent(_GeneratedChunksContainer)  # Reparent the generated chunk to the generated chunks container
	generatedChunk.global_position = Position
	
	# Set chunk script parameters
	generatedChunk._Seed = CalculateSeedForObject(ChunkRandomizeMode, generatedChunk, _RNG, -1, generatedChunk.global_position)
	generatedChunk._NearbyChunkIdxs = NearbyChunks
	generatedChunk._UpdateParameters()
	generatedChunk._UpdateModulesParameters()
	generatedChunk._RunModules()
	
	# Return the generated chunk
	return generatedChunk

func GenerateNearbyChunks(PlayerPosition: Vector3) -> void:
	# PlayerPosition must be the GLOBAL POSITION
	# NOTE: This function is VERY computational expensive, please avoid calling it a lot
	
	# Get the chunk where the player is
	var playerChunk = GetPlayerCurrentChunk(PlayerPosition)
	
	# Specify the floors that will be generated (relative to the player's position)
	var floorsToGenerate = [0]  # Default is just one floor
	
	# If it's not running on a server
	if (!Utilities.IsServer()):
		# Add the floors downward (for floor preprocessing)
		if (MaxFloors.x != 0):
			floorsToGenerate.append_array(range(-absi(MaxFloors.x)))
		
		# Add the floors upward (for floor preprocessing)
		if (MaxFloors.y != 0):
			floorsToGenerate.append_array(range(absi(MaxFloors.y)))
	
	# For every floor (y)
	for y in floorsToGenerate:
		# Get the image for the floor
		var floorImage = GetFloorTexture(playerChunk.y + y)
		
		# Create a dictionary with the chunks to generate
		var chunksToGenerate = {}
		
		# From -x to +x (relative to the player)
		for x in range(playerChunk.x - GenerationRadius, playerChunk.x + GenerationRadius):
			# From -z to +z (relative to the player)
			for z in range(playerChunk.z - GenerationRadius, playerChunk.z + GeneralChunkSize):
				# Add to the chunks to generate dictionary the chunk position (key) and the chunk index (value)
				chunksToGenerate[Vector3i(x, y * GeneralChunkSize.y, z)] = GetChunkIndexFromFloorTexture(floorImage, Vector2i(x, y))
		
		# For every chunk position in the dictionary of the chunks to generate
		for chunkPos in chunksToGenerate.keys():
			# Calculate nearby chunks and get their indexes
			var leftChunk = chunkPos - Vector3i(1, 0, 0)
			var rightChunk = chunkPos + Vector3i(1, 0, 0)
			var backChunk = chunkPos - Vector3i(0, 0, 1)
			var frontChunk = chunkPos + Vector3i(0, 0, 1)
			
			# If the nearby chunk is already in the dictionary of the chunks to generate, avoid recalculation
			leftChunk = chunksToGenerate.get(leftChunk, GetChunkIndexFromFloorTexture(floorImage, Vector2i(leftChunk.x, leftChunk.z)))
			rightChunk = chunksToGenerate.get(rightChunk, GetChunkIndexFromFloorTexture(floorImage, Vector2i(rightChunk.x, rightChunk.z)))
			backChunk = chunksToGenerate.get(backChunk, GetChunkIndexFromFloorTexture(floorImage, Vector2i(backChunk.x, backChunk.z)))
			frontChunk = chunksToGenerate.get(frontChunk, GetChunkIndexFromFloorTexture(floorImage, Vector2i(frontChunk.x, frontChunk.z)))
			
			# Generate the chunk
			GenerateChunk(chunkPos, chunksToGenerate[chunkPos], [leftChunk, rightChunk, backChunk, frontChunk])
		
		# Clear the dictionary
		chunksToGenerate.clear()

func DeleteChunks(PlayersPosition: Array[Vector3i]) -> void:
	# PlayersPosition must have the GLOBAL POSITION
	# For each generated chunk
	for chunk in _GeneratedChunksContainer.get_children(false):
		# Create new variable and set to to true by default. This variable controls wether the chunk should be deleted or not
		var delete = true
		
		# For each player position
		for playerPos in PlayersPosition:
			# Make sure the chunk distance is less or equals the generation radius
			if (chunk.global_position.distance_to(playerPos) <= GenerationRadius):
				# The chunk is nearby a player; do not delete
				delete = false
				break
		
		# Delete the chunk if it should be deleted
		if (delete):
			chunk.queue_free()

func GetPlayerCurrentChunk(PlayerPosititon: Vector3) -> Vector3i:
	# PlayerPosition must be the GLOBAL POSITION
	return Vector3i(
		roundi(PlayerPosititon.x / GeneralChunkSize.x),
		roundi(PlayerPosititon.y / GeneralChunkSize.y),
		roundi(PlayerPosititon.z / GeneralChunkSize.z)
	)

func _UpdateParameters() -> void:
	_RNG.seed = _Seed

func _ready() -> void:
	# Get chunk constants (all children nodes, MUST BE Node3D)
	var chunks = get_children(false)
	
	# Create container for the generated chunks
	_GeneratedChunksContainer = Node3D.new()
	_GeneratedChunksContainer.name = "Generated chunks"
	add_child(_GeneratedChunksContainer)
	
	# Create container for the chunk constants
	_ChunkConstants = Node3D.new()
	_ChunkConstants.name = "Constants"
	_ChunkConstants.process_mode = Node.PROCESS_MODE_DISABLED
	add_child(_ChunkConstants)
	
	# Move all the chunk constants to its container
	for chunk in chunks:
		# Reparent the chunk
		chunk.reparent(_ChunkConstants, true)
		
		# Move the chunk to an unreachable position
		chunk.global_position = Vector3(-99999, -99999, -99999)
