class_name LevelGeneration extends Node3D

enum NoiseMapType
{
	ALL_BLACK = 0,
	ALL_WHITE = 1,
	PERLIN_NOISE = 2
}

var _GeneratedChunksContainer: Node3D
var _ChunkConstants: Node3D

@export_category("Generation")
var GenerationRadius: int = 20  # Radius where the chunks will be generated

@export_group("Noise maps")
@export var NoiseMaps: Dictionary[String, Image] = {}
@export var DefaultNoiseMapType: NoiseMapType = NoiseMapType.PERLIN_NOISE
@export var DefaultNoiseMapSize: Vector2i = Vector2i(1024, 1024)

@export_group("Floors")
@export var MaxFloors: Vector2i = Vector2i(0, 0)  # X = down limit, Y = up limit, (0, 0) = no floors
@export var PreloadFloors: Vector2i = Vector2i(0, 0)  # Number of floors to preload. X = down, Y = up, (0, 0) = no preload
# More abour preloaded floors:
# Preloaded floors are NOT generated by the server; only by the client
# Because of this, preloaded floors might not have items nor entities, until the player goes there

@export_category("Chunks")
@export var GeneralChunkSize: Vector3 = Vector3(20, 6, 20)

func CreateFloorImage() -> Image:
	const FORMAT = Image.FORMAT_RGBA8
	var img
	
	# Check image type
	match DefaultNoiseMapType:
		NoiseMapType.ALL_BLACK:
			# Create black image
			img = Image.create(DefaultNoiseMapSize.x, DefaultNoiseMapSize.y, false, FORMAT)
			img.fill(Color.BLACK)
		NoiseMapType.ALL_WHITE:
			# Create white image
			img = Image.create(DefaultNoiseMapSize.x, DefaultNoiseMapSize.y, false, FORMAT)
			img.fill(Color.WHITE)
		NoiseMapType.PERLIN_NOISE:
			# Create an image with perlin noise
			var perlin = FastNoiseLite.new()
			perlin.noise_type = FastNoiseLite.TYPE_PERLIN
			
			img = perlin.get_image(DefaultNoiseMapSize.x, DefaultNoiseMapSize.y, false, false, true)
		_:
			# Invalid option; push error
			push_error("Invalid NoiseMapType. Image will not be generated (null will be returned instead).")
	
	# Return the image
	return img

func GetFloorTexture(Floor: int) -> Image:
	# Create null variable
	var img = null
	
	# For each key in the noise maps (example of a key: "0,1,5")
	for floorsUnparsed in NoiseMaps.keys():
		# Split the string and for each new string (example: "0")
		for floorIDX in floorsUnparsed.split(","):
			# Strip the edges of the string (example: " 0 " => "0")
			floorIDX = floorIDX.strip_edges(true, true)
			
			# Parse the string as an integer (example: "0" => 0)
			floorIDX = int(floorIDX)
			
			# Check if the desired floor is this one
			if (Floor == floorIDX):
				# It is! Set the image with the noise map and stop the loop
				img = NoiseMaps[floorsUnparsed]
				break
		
		# Stop the loop of the image is set (the desired floor was found)
		if (img != null):
			break
	
	# If the image is not set (the desired floor was not found), create an image
	if (img == null):
		img = CreateFloorImage()
	
	# Return the image
	return img

func GenerateNearbyChunks(PlayerPosition: Vector3) -> void:
	pass  # TODO

func DeleteChunks(PlayersPosition: Array[Vector3]) -> void:
	# For each generated chunk
	for chunk in _GeneratedChunksContainer.get_children(false):
		# Create new variable and set to to true by default. This variable controls wether the chunk should be deleted or not
		var delete = true
		
		# For each player position
		for playerPos in PlayersPosition:
			# Make sure the chunk distance is less or equals the generation radius
			if (chunk.global_position.distance_to(playerPos) <= GenerationRadius):
				# The chunk is nearby a player; do not delete
				delete = false
				break
		
		# Delete the chunk if it should be deleted
		if (delete):
			chunk.queue_free()

func _ready() -> void:
	# Get chunk constants (all children nodes, MUST BE Node3D)
	var chunks = get_children(false)
	
	# Create container for the generated chunks
	_GeneratedChunksContainer = Node3D.new()
	_GeneratedChunksContainer.name = "Generated chunks"
	add_child(_GeneratedChunksContainer)
	
	# Create container for the chunk constants
	_ChunkConstants = Node3D.new()
	_ChunkConstants.name = "Constants"
	add_child(_ChunkConstants)
	
	# Move all the chunk constants to its container
	for chunk in chunks:
		# Reparent the chunk
		chunk.reparent(_ChunkConstants, true)
		
		# Move the chunk to an unreachable position
		chunk.global_position = Vector3(-99999, -99999, -99999)
